### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by obsidienne** [jesseshieh/master_proxy#1]
Hi,

I have an umbrella app with one app for ecto and one app for web/api. I want to split the api from the web part to have 3 app (db / api / web).

Is it possible to create a fourth app "proxy" containing only your lib and doing the work ?
I can't make it work. Do you have an exemple app where everything is split ?

thanks

**Comment by jesseshieh** [comment]
Hi, sorry for the late reply, I'm not sure how I missed this. When you say you can't make it work, what issue do you run into? Do you get an error of some kind?

Here is an [example commit](https://github.com/gigalixir/gigalixir-getting-started/commit/e19c719c23b495590bea18a3c890fdc32daf77ab) where I installed master_proxy, but it isn't an umbrella app. It should work the same, though.

**Comment by obsidienne** [comment]
Hi, thanks for your answer.

I have made it work, but I think it can be simple. I have scaffold an empty phoenix app in my umbrella named proxy and added to it your lib.

Maybe there is a way to cut 80% of this umbrella app but I'm not sure how to do it... 

This ticket was about creating a proxy as an app in the umbrella. This way I can visually separate the proxy for my other apps.

Thanks

**Comment by jesseshieh** [comment]
Oh I see what you mean. This repo was based off of acme_bank which has the master_proxy has a separate app. Maybe looking through how they did it would help. See https://github.com/wojtekmach/acme_bank/tree/master/apps/master_proxy
