### ISSUE TITLE
Increased flexibility

### ISSUE THREAD

**Issue by axelson** [jesseshieh/master_proxy#13]
I'm working on running multiple phoenix applications on nerves on top of vultr cloud hosting (using https://github.com/nerves-project/nerves_system_vultr). With this setup it is difficult to run a reverse proxy such as nginx, so I'd like to use master_proxy as a proxy to the different applications but am running into some difficulties. I wrote a little more background in https://github.com/sasa1977/site_encrypt/issues/26

I have made some local changes to master_proxy that allows me to use it in this setup, along with some other enhancements that (I feel) make it more usable and flexible (you can preview the changes in my repo if you'd like: https://github.com/axelson/master_proxy/tree/flexiblity-1 although I need to clean it up still)

Feature requests:
1. Ability to inject configuration into master_proxy
  - This is important for me to set `SiteEncrypt.https_keys/1` as part of the configuration so that I can serve https traffic from master_proxy
  - In my implementation this is the `merge_config/2` callback function
2. Ability to start master_proxy as part of your supervision tree
  - This is important to me because master proxy need's configuration from site_encrypt, and the site_encrypt configuration `SiteEncrypt.https_keys/1` is not available until after site_encrypt is running so I need better control over when master_proxy starts
3. Ability to control which endpoint is chosen by passing in `domain`
  - This isn't really that important but I think it makes it more easy to use master_proxy in the common case of serving two separate websites/domains (it is my perception that two or more separate domains is the most common use-case for master_proxy)
4. Allow the user to use a function to decide the endpoint to call at runtime
  - This isn't necessarily that important either, but I think it is a nice API
  
Before I clean up my changes to submit them as a formal PR, I wanted to let you know and solicit feedback. 1 and 2 are solved by creating a behaviour and having the user create a proxy module that has `use MasterProxy` and pass in the arguments from there, when gives user's the flexibility if they want to use the application environment, which I think is in the spirit of the official library guidelines: https://hexdocs.pm/elixir/library-guidelines.html#avoid-application-configuration

**Comment by jesseshieh** [comment]
These are great suggestions! Starting master_proxy as part of the supervision tree has also been proposed and implemented here, but exists as a separate repo.
https://github.com/jesseshieh/master_proxy/pull/9

To be honest, this was just a quick and dirty implementation that solved the problem, and I welcome all these changes, but I'm not sure if I have too much time to really dig into this deeply. Would you like to become the maintainer of this project and take it in whatever direction you feel is right?

**Comment by axelson** [comment]
Hi @jesseshieh, after thinking about it a bit, I would be glad to become the maintainer. Although my plan is to form a group of elixir developers that would be willing to collectively maintain a few libraries. And thanks for the link to that other PR.
