### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by axelson** [jesseshieh/master_proxy#18]
@jesseshieh can we change the default branch of this repo to `main`? I'm trying to change it on all of the repos that I am a part of.

**Comment by jesseshieh** [comment]
I don't see why not!

**Comment by axelson** [comment]
Great! Can you either make the change or give me the permissions to? I think I need the admin role.

**Comment by jesseshieh** [comment]
I just looked around the settings, but couldn't see any other roles other than collaborator. Anyway, I went ahead and changed the base branch to `main`.

**Comment by axelson** [comment]
Ah, maybe that's a limitation of the free version of GitHub. Thanks for updating the default branch!
