### ISSUE TITLE
Update `main_proxy` to support Phoenix 1.7

### ISSUE THREAD

**Issue by elepedus** [jesseshieh/master_proxy#28]
Having upgraded an umbrella app to Phoenix 1.7, `main_proxy` errors out because `Phoenix.Endpoint.Cowboy2Handler` has been removed. 

```
[error] Ranch protocol #PID<0.747.0> of listener HTTP (connection #PID<0.746.0>, stream id 1) terminated
an exception was raised:
    ** (UndefinedFunctionError) function Phoenix.Endpoint.Cowboy2Handler.init/2 is undefined (module Phoenix.Endpoint.Cowboy2Handler is not available)
        Phoenix.Endpoint.Cowboy2Handler.init(%{...}, {MyApp.Endpoint, []})
        (cowboy 2.9.0) /app_umbrella/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /app_umbrella/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) //app_umbrella/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

```

**Comment by axelson** [comment]
Thanks for the report! It does definitely sound like MainProxy needs an update to support Phoenix 1.7. I'll do my best to get it ready before 1.7 is fully released.

**Comment by elepedus** [comment]
I've just submitted a PR. It probably needs some work (my first Elixir PR!), but the tests pass, so it may be a reasonable starting point. https://github.com/Main-Proxy/main_proxy/pull/29

**Comment by axelson** [comment]
For anyone watching this issue, please check out #31 and let me know how it goes! If it goes well then I'll cut a release soon (tm)
