### ISSUE TITLE
Dependency conflict for plug_cowboy

### ISSUE THREAD

**Issue by DavidOliver** [jesseshieh/master_proxy#5]
I believe Phoenix's dependency on `plug_cowboy` is set to `~> 2.0`. This resulted in mix getting version `2.1.0` and setting that in the lock file.

I'm going from memory after having been through the process, but I believe installing `master_proxy` threw up a conflict, with its `~> 2.0.0` seeming to conflict with my `mix.lock`'s `2.1.0`.

To get round it, I set the following in all my umbrella project's endpoint apps' deps:

    {:plug_cowboy, "~> 2.1", [override: true]}

Am I right in thinking that this could be avoided by using `~> 2.0` in `master_proxy`'s deps, to match Phoenix's dep?

Thanks for the very useful library!

**Comment by jesseshieh** [comment]
Oh, good catch! Happy to accept a pull request if you have time.

**Comment by DavidOliver** [comment]
Thanks for confirming - I need to read up on the semantics of the various ways of specifying versions. I'll do so and send a PR tomorrow.
